name: Deploy

on:
  push:
    branches:
      - main
#UPDATE?
jobs:
  deploy:
    runs-on: [Deployment]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rebuild application
        run: |
          docker compose up -d --build
